### ISSUE TITLE
Models folder does not exist

### ISSUE THREAD

**Issue by jque4** [johnnysong-cc/COMP309Proj2#6]
https://github.com/johnnysong-cc/COMP309Proj2/blob/ee0b4df61ed6829255010aa3eeffb01bd59c6764/app.py#L57
App.py does not run due to the missing models folder.

Models need to be generated and added to the models folder in order to run correctly.

**Comment by johnnysong-cc** [comment]
Don't try with files in `logic/` yet. As the comment in my commit says: API halfway done. Go for `logic_scripts/` for now. Thanks.
